# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.problems.report=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=4.5.1
maven_group=com.alexeys.translate_allinone
archives_base_name=translate-all-in-one

# Dependencies
fabric_version=0.152.1+26.2
modmenu_version=20.0.0-beta.2